### ISSUE TITLE
Not getting demo to work: `WebAssembly.instantiate(): expected magic word...`

### ISSUE THREAD

**Issue by rebz** [technokrat-llc/vuexr#1]
When attempting a `demo:serve` I am unable to access the localhost from my WiFi network. Normally this is done by inputting the IP Address of the computer and the port (9000).

It works in the browser but I have no camera attached.

I then tried `demo:build` and hosted the code on a website to test against, and I receive the following console error.

![image](https://user-images.githubusercontent.com/628385/75182613-c422e000-570e-11ea-9f60-e2ba015e0164.png)

**Comment by rebz** [comment]
Worth noting I am using Node 12.13.0

**Comment by Atokulus** [comment]
Hi @rebz

Thanks for testing out vuexr and the screenshot (you must be the first 😄). I will soon offer an online demo myself.

To make `vuexr` run, you have to follow up two steps from the documentation, you probably were not aware of. I will extend these sections in the future, so nobody misses them.
`vuexr` should work under Node 12.13.0 if I am not mistaken horribly.

### Secure Context

Only `localhost` or `HTTPS` to your server will work, as the [MediaDevices API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices) requires a [secure context](https://w3c.github.io/webappsec-secure-contexts/) to open up a camera, as the user's privacy is at stake.

To make this works for demo purposes I suggest to use the `chrome://inspect` NAT feature on Chromium based browsers.

### Public accessible `opencv_js.wasm` file
OpenCV builds its own JavaScript wrapper around the [opencv_js.wasm](https://github.com/technokrat-llc/vuexr/blob/master/vendor/opencv_js.wasm) binary. To let `opencv.js` load the WASM file asynchronously, you need to add it to your public/static server folder. See the [README](https://github.com/technokrat-llc/vuexr/blob/master/README.md) if you are using Webpack.

You also have to make [worker.js](https://github.com/technokrat-llc/vuexr/blob/master/dist/worker.js) publicly available, which you seem to have done 👍 

```javascript
// vue.config.js
const path = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  // ...
  configureWebpack: {
    plugins: [
      new CopyWebpackPlugin([
        {
          from: path.join(__dirname, 'node_modules/vuexr/vendor/opencv_js.wasm'),
          to: 'opencv_js.wasm'
        },
        {
          from: path.join(__dirname, 'node_modules/vuexr/dist/worker.js'),
          to: 'worker.js'
        }
      ])
    ]
  }
  // ...
}
```


Thanks for your time. If you need any help to get these steps working, you are welcome to post in this issue.

Best regards
Markus

**Comment by Atokulus** [comment]
I added a `TLDR` section in 6c53ecc85317f44d7061116c09044c27980e1c46 so nobody should be able to miss these steps.

We should also add a `UI` and `console.log`-based error message in the future, checking for these errors, in hinting `vuexr` users in the right direction.

**Comment by rebz** [comment]
@Atokulus - Thank you for the information. I will attempt this again today and get back to you.

**Comment by Atokulus** [comment]
Hi @rebz 
There is now a working demo at [https://vuexr.technokrat.ch](https://vuexr.technokrat.ch)

Enjoy (hopefully 😉)

Best regards
Markus
